# docker-compose.yml (Definitive Final Version)
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      # Explicitly set the NameNode's own HTTP address
      - HDFS_CONF_dfs_namenode_http_address=namenode:9870

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      # This forces the DataNode to advertise its correct web address
      HDFS_CONF_dfs_datanode_http_address: "datanode:9864"
      # --- THIS IS THE FINAL CRUCIAL FIX ---
      # This forces the DataNode to advertise its correct internal RPC address
      HDFS_CONF_dfs_datanode_address: "datanode:9866"
    depends_on:
      - namenode

  client:
    build: .
    container_name: python-client
    depends_on:
      - namenode
      - datanode
    volumes:
      - .:/app

volumes:
  hadoop_namenode:
  hadoop_datanode: